config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name,
          presence: true,
          uniqueness: { case_sensitive: false },
          length: {minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  
  before_save { self.email = email.downcase }

  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 150 },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(articles_params)
    @article.user = current_user
    
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(articles_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article was successfully deleted"
    end

    redirect_to articles_path
  end

  private

    def articles_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def set_article
      @article = Article.find(params[:id])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5).order('name')
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category was successfully created"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end

    def require_admin
      if !logged_in? || (logged_in? and !current_user.admin?)
        flash[:danger] = "Only admins can perform that action"
        redirect_to categories_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    session_params = params[:session]
    user = User.find_by(email: session_params[:email].downcase)
    
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to articles_path
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5).order('username')
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was successfully updated"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    flash[:danger] = "User #{@user.username} and all their articles have been deleted"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only admins can perform that action"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{gravatar_size}"
    
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/views/articles/_articles_list.html.erb
<div class="section-content articles-list">

  <% obj.each do |article| %>
    <article class="article">
      <h4 class="article__title"><%= link_to article.title, article_path(article) %></h2>
      <p class="article__meta">
        <span class="article__author">created by <%=link_to article.user.username, user_path(article.user) %></span>
        <span class="article__time"><%= time_ago_in_words(article.created_at) %> ago, last updated <%= time_ago_in_words(article.updated_at) %> ago.</span>

        <% if article.categories.any? %>
          <span class="article__categories">
            In categories <%= render article.categories %>
          </span>
        <% end %>
      </p>
      <p class="article__body"><%= truncate(article.description, lenght: 50) %></p>

      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
      <div class="row">
        <%= link_to 'Delete', article_path(article),
          method: :delete,
          data: {confirm: "Are you sure you want to delete article '#{article.title}'?"},
          class: "button button-danger" %>
        <%= link_to 'Edit', edit_article_path(article), class: "button" %>
      </div>
      <% end %>
      
    </article>
  <% end %>

</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', object: @article %>

<%= form_for @article do |f| %>

<div class="eight columns offset-by-two">
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, class: "u-full-width" %>
  </p>

  <p>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, class: "u-full-width" %>
  </p>

  <p>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label() {cb.check_box() + cb.text} %>
    <% end %>
  </p>

  <p>
    <%= f.submit class: "button button-primary" %>
  </p>
</div>

<% end %>

app/views/articles/edit.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">Editing Article</h2>
    <%= link_to 'Back to listing', articles_path, class: "button" %>
  </div>
</div>

<div class="section-content">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">All Articles</h2>

    <% if logged_in? %>
      <%= link_to 'New article', new_article_path, class: "button" %>
    <% end %>
  </div>
</div>

<div class="row">
  <%= will_paginate %>
</div>

<%= render 'articles_list', obj: @articles %>

<div class="row">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">New Article</h2>
    <%= link_to 'Back to listing', articles_path, class: "button" %>
  </div>
</div>

<div class="section-content">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="row">
  <div class="section-actions">
    
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to 'Delete', article_path(@article),
        method: :delete,
        data: {confirm: "Are you sure you want to delete article '#{@article.title}'?"},
        class: "button button-danger" %>
      <%= link_to 'Edit', edit_article_path(@article), class: "button" %>
    <% end %>

    <%= link_to 'Back to listing', articles_path, class: "button" %>
    
  </div>
</div>

<div class="section-content">

  <article class="article">
    <h2 class="article__title"><%= @article.title %></h2>
    <div class="article__meta">

      <ul class="article__author user-data__list">
        <li>Create by</li>
        <li class="user-data__image"><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
        <li class="user-data__username"><%= link_to @article.user.username, user_path(@article.user) %></li>
        <li class="user-data__articles-count"><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></li>
      </ul>

      <p class="article__time"><%= time_ago_in_words(@article.created_at) %> ago, last updated <%= time_ago_in_words(@article.updated_at) %> ago</p>

      <% if @article.categories.any? %>
        <div class="article__categories">
          <%= render @article.categories %>
        </div>
      <% end %>
    </div>
    <p class="article__body"><%= @article.description %></p>
  </article>

</div>

app/views/categories/_category.html.erb
<span class="category pill"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', object: @category %>

<%= form_for @category do |f| %>

<div class="eight columns offset-by-two">
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, class: "u-full-width" %>
  </p>
  <p>
    <%= f.submit class: "button button-primary" %>
  </p>
</div>

<% end %>

app/views/categories/edit.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">Editing Category</h2>
    <%= link_to 'Back to listing', categories_path, class: "button" %>
  </div>
</div>

<div class="section-content">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">All categories</h2>

    <% if logged_in? and current_user.admin? %>
      <%= link_to 'New category', new_category_path, class: "button" %>
    <% end %>
  </div>
</div>

<div class="row categories-list">
  <div class="eight columns offset-by-two">

    <div class="row">
      <%= will_paginate %>
    </div>

    <div class="category-data">
      <ul class="category-data__list">
        <% @categories.each do |category| %>

          <%= link_to(category_path(category)) do %>
            <li class="pill">
              <span class="category-data__name"><%= category.name %></span>
              <span class="category-data__articles-count"><%= pluralize(category.articles.count, "article") if category.articles %></span>
            </li>
          <% end %> 

        <% end %>
      </ul>
    </div>

    <div class="row">
      <%= will_paginate %>
    </div>

  </div>
</div>

app/views/categories/new.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">New Category</h2>
    <%= link_to 'Back to listing', categories_path, class: "button" %>
  </div>
</div>

<div class="section-content">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">Category <%= @category.name %></h2>

    <% if logged_in? and current_user.admin? %>
      <%= link_to 'Edit', edit_category_path(@category), class: "button" %>
    <% end %>

    <%= link_to 'Back to listing', categories_path, class: "button" %>
  </div>
</div>

<div class="row">
  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/articles_list', obj: @category_articles %>

<div class="row">
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="site-footer">
  <div class="container">
    <small>Copyright &copy; <a href="http://diegoversiani.me">Diego Versiani</a> | <%= link_to 'About', about_path %> | <a href="https://github.com/diegoversiani/alpha-blog">See code on GitHub</a></small>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% unless flash.blank? %>
<div class="messages messages--success">
  <ul class="messages__list">
  <% flash.each do |name, msg| %>
    <li class="messages__item"><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <div class="section-wrapper">

    <div class="brand"><%= link_to 'Alpha blog', root_path %></div>

    <ul class="menu main-navigation">
      <li class="menu__item"><%= link_to 'Articles', articles_path %></li>
      <li class="menu__item"><%= link_to 'Categories', categories_path %></li>
      <li class="menu__item"><%= link_to 'Bloggers', users_path %></li>

      <% if logged_in? %>
        <% profile_link_text = current_user.admin? ? "Your Profile (admin)" : "Your Profile" %>
        <li class="menu__item"><%= link_to profile_link_text, user_path(current_user) %></li>
        <li class="menu__item"><%= link_to 'Log out', logout_path, method: :delete, class: "button button-primary" %></li>
      <% else %>
        <li class="menu__item"><%= link_to 'Log in', login_path, class: "button button-primary" %></li>
        <li class="menu__item"><%= link_to 'Sign up', signup_path, class: "button button-primary" %></li>
      <% end %>

    </ul>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="main container">
  
  <%= render 'layouts/messages' %>
  
  <%= yield %>

</div>

<%= render 'layouts/footer' %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<article>
  <h1>About Alpha Blog</h1>

  <p>This is a blog application made with Ruby on Rails during The Complete Ruby on Rails Developer Course</p>

  <h2>Technologies</h2>

  <ul>
    <li>This project was developed using:
      <ul>
        <li>Ruby 2.2.3</li>
        <li>Rails 4.2.6</li>
        <li>Skeleton CSS Boilerplate</li>
      </ul>
    </li>
  </ul>

  <p><a href="https://github.com/diegoversiani/alpha-blog">See code on GitHub</a></p>
</article>

app/views/pages/home.html.erb
<div class="cta">
  <div class="container">
    <h1>Welcome to Alpha Blog</h1>

    <%= link_to 'Sign up now', signup_path, class: 'button button-primary' %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="messages messages--errors eight columns offset-by-two">
      <h5><%= pluralize(object.errors.count, "error")%> prevented from being saved:</h5>
      <ul class="messages__list">
      <% object.errors.full_messages.each do |msg| %>
        <li class="messages__item"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>

<%= form_for @user do |f| %>

<div class="eight columns offset-by-two">
  <p>
    <%= f.label :username %>
    <%= f.text_field :username, class: "u-full-width" %>

    <%= f.label :email %>
    <%= f.email_field :email, class: "u-full-width" %>

    <%= f.label :password %>
    <%= f.password_field :password, class: "u-full-width" %>
  </p>

  <p>
    <%= f.submit (@user.new_record? ? "Sign up" : "Update your account"), class: "button button-primary" %>
  </p>
</div>

<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">Edit your account</h2>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
  <div class="section-actions">
    <h2 class="section-title">All Alpha Bloggers</h2>
  </div>
</div>

<div class="row users-list">
  <div class="eight columns offset-by-two">
    
    <div class="row">
      <%= will_paginate %>
    </div>

    <% @users.each do |user| %>
      <div class="user-data">
        <ul class="user-data__list">
          <li class="user-data__image"><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="user-data__username"><%= link_to user.username, user_path(user) %></li>
          <li class="user-data__articles-count"><%= pluralize(user.articles.count, "article") if user.articles %></li>
          <% if logged_in? and current_user.admin? %>
          <li class="user-data__actions">
            <%= link_to 'Delete', user_path(user),
                    method: :delete,
                    data: {confirm: "Are you sure you want to delete the user and all their articles?"},
                    class: "button button-danger" %>
          </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <%= will_paginate %>
    </div>

  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="section-actions twelve columns">
    <h2 class="section-title">Sign up</h2>
  </div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="section-actions">

    <% if logged_in? && current_user == @user %>
    <%= link_to 'Edit account', edit_user_path(current_user), class: "button" %>
    <% end %>
    
  </div>
<div class="row">

<div class="row profile">
  <h2 class="profile__name"><%= @user.username %>'s page</h2>
  <%= gravatar_for @user, size: 150 %>
</div>

<div class="row">
  <h5 class="user-articles__title"><%= @user.username %>'s articles</h5>

  <div class="row">
    <%= will_paginate @user_articles %>
  </div>

  <%= render 'articles/articles_list', obj: @user_articles %>

  <div class="row">
    <%= will_paginate @user_articles %>
  </div>

</div>